// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqypxdqqffnfilotzygy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxeXB4ZHFxZmZuZmlsb3R6eWd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU0NTA5NjUsImV4cCI6MjA4MTAyNjk2NX0.VCr3AyaSV1JburGLF4RBnhnlF_n8f9aKcV5jXjyHsXQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});